version: "3"

services:
  webserver:
    build: 
      context: ./bin/${PHP_VERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${PHP_VERSION}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - "database"
    volumes: 
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2      
  database:
    platform: linux/amd64
    build:
      context: "./bin/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-database'
    # command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PMA_PORT: ${HOST_MACHINE_MYSQL_PORT}
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
      USER_UID: 1000
      USER_GID: 1000
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/docker-entrypoint-initdb.d
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      # - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
  phpmyadmin:
    # platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    links:
      - "database"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
    volumes: 
      - phpmyadmin-sessions:/sessions
      - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
      - ${PHP_CONFIG_INC-../config/php/config.inc.php}:/etc/phpmyadmin/config.inc.php
  redis:
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    image: redis:latest
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"
volumes:
  phpmyadmin-sessions: